apiVersion: v1
kind: Service
metadata:
  name: questionlair-api
  namespace: questionlair-be
spec:
  selector:
    app: questionlair-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
