apiVersion: v1
kind: Service
metadata:
  name: questionlair-web
  namespace: questionlair-fe
spec:
  selector:
    app: questionlair-web
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
