apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: questionlair-db
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-49x-1t6

---
# MinIO PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  namespace: questionlair-db
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-49x-1t6
