apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: questionlair-db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer 
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: questionlair-db
spec:
  selector:
    app: db
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer
