apiVersion: v1
kind: Service
metadata:
  name: llm-api-service
  namespace: questionlair-llm
spec:
  type: LoadBalancer
  selector:
    app: llm-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
